### ISSUE TITLE
Tests are installed as package 

### ISSUE THREAD

**Issue by sgaisser** [us-irs/spacepackets-py#94]
Currently, the tests are installed as own package and show up in the python environment if the package is installed with pip.

Maybe add 

```toml
[tool.setuptools.packages.find]
exclude = ["docs", "tests*"]
```

to the pyrpoject.toml. Idk if this works.
